// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $channels from "./routes/channels.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $player from "./routes/player.tsx";
import * as $Channels from "./islands/Channels.tsx";
import * as $Index from "./islands/Index.tsx";
import * as $Loader from "./islands/Loader.tsx";
import * as $Player from "./islands/Player.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/channels.tsx": $channels,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/player.tsx": $player,
  },
  islands: {
    "./islands/Channels.tsx": $Channels,
    "./islands/Index.tsx": $Index,
    "./islands/Loader.tsx": $Loader,
    "./islands/Player.tsx": $Player,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
